# -*- coding: utf-8 -*-
{
    'name': 'Studio customizations',
    'version': '14.0.1.0',
    'category': 'Studio',
    'description': u"""

This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.

""",
    'author': 'My Company (San Francisco)',
    'depends': [
        'account',
        'base',
        'de_fuel_management',
        'de_purchase_budget',
        'de_purchase_pricelist',
        'de_purchase_subscription',
        'de_stock_material_transfer',
        'de_stock_material_transfer_approvals',
        'hr_expense',
        'product',
        'project',
        'purchase',
        'purchase_stock',
        'stock',
        'web_studio',
    ],
    'data': [
        'data/res_groups.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'data/ir_model_access.xml',
        'data/ir_default.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
